---
title: "Capstone Group Evaluations"
author: "Jasmine Merrill"
date: "12/15/2021"
output: html_notebook
---


## Who are you evaluating?

Eli Freedman




# Evaluation Areas

### 1. Intellectual Contributions.

*Understanding the project, doing the research, evaluating and interpreting data, creative efforts and problem solving insight, providing intellectual leadership for group.* 

Score (out of 10): 10

Justification/Examples: Eli always was the person on top of getting things done and making sure everything was done on time. He was very helpful with any problems me or my teammates ran into during the project. 




### 2. Team Support.

*Enthusiasm, commitment to project, cooperation, respect for other persons’ ideas, willingness to compromise as appropriate, receptiveness to constructive feedback.* 

Score (out of 10): 10

Justification/Examples: Always listened to everyone's idea before deciding what was best for the group. Was always willing to help others no matter what. Overall a great team player in this group.




### 3. Communication Contributions. 

*Effectiveness of communication within team, quality of written work, contributions toward creation of presentation and other written work.* 

Score (out of 10): 10

Justification/Examples: Eli was very easy to reach and wa salways on top of the work and deadlines. Helped look over all of our work to make sure it was all cleaned-up and ready to submit. Very good at communication.




### 4. Time Contributions.

*Keeping team on task, meeting deadlines, following through on plans, attendance at team meetings, does equal share of work.* 

Score (out of 10): 10

Justification/Examples: Always helped us stay on track and split up the work fairly.





### 5. Overall / Other Contributions

*Score any additional contributions, general remarks, or overall impression of this person as a member of the group.*


Score (out of 10): 10

Justification/Examples: Eli was a great person to work with and really had a good understandig of the material from class. 





# Total Score (out of 50): 50





