---
title: "Capstone Group Evaluations"
author: "YOUR NAME"
date: ""
output: html_notebook
---


## Who are you evaluating?

*Full name of team member you are evaluating, or say "self-evaluation"*




# Evaluation Areas

### 1. Intellectual Contributions.

*Understanding the project, doing the research, evaluating and interpreting data, creative efforts and problem solving insight, providing intellectual leadership for group.* 

Score (out of 10): ___

Justification/Examples:




### 2. Team Support.

*Enthusiasm, commitment to project, cooperation, respect for other persons’ ideas, willingness to compromise as appropriate, receptiveness to constructive feedback.* 

Score (out of 10): ___

Justification/Examples:




### 3. Communication Contributions. 

*Effectiveness of communication within team, quality of written work, contributions toward creation of presentation and other written work.* 

Score (out of 10): ___

Justification/Examples:




### 4. Time Contributions.

*Keeping team on task, meeting deadlines, following through on plans, attendance at team meetings, does equal share of work.* 

Score (out of 10): ___

Justification/Examples:





### 5. Overall / Other Contributions

*Score any additional contributions, general remarks, or overall impression of this person as a member of the group.*


Score (out of 10): ___

Justification/Examples:





# Total Score (out of 50): 





